#############################################################################
# Makefile for building: SimpleTeacher
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sun Nov 3 22:24:18 2013
# Project:  SimpleTeacher.pro
# Template: app
# Command: /usr/bin/qmake -unix QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile SimpleTeacher.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/gcc
CXX           = /usr/bin/g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -g3 -gdwarf-2 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -g3 -gdwarf-2 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Igui -Ibuild -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/Dictionary.cc \
		src/Lexicon.cc \
		src/main.cc \
		src/Word.cc \
		gui/MainWindow.cc build/moc_MainWindow.cpp
OBJECTS       = build/Dictionary.o \
		build/Lexicon.o \
		build/main.o \
		build/Word.o \
		build/MainWindow.o \
		build/moc_MainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SimpleTeacher.pro
QMAKE_TARGET  = SimpleTeacher
DESTDIR       = 
TARGET        = SimpleTeacher

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_main.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SimpleTeacher.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -unix QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile SimpleTeacher.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 -o Makefile SimpleTeacher.pro

dist: 
	@$(CHK_DIR_EXISTS) build/SimpleTeacher1.0.0 || $(MKDIR) build/SimpleTeacher1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/SimpleTeacher1.0.0/ && $(COPY_FILE) --parents Dictionary.h Lexicon.h Word.h gui/MainWindow.h build/SimpleTeacher1.0.0/ && $(COPY_FILE) --parents Dictionary.cc Lexicon.cc main.cc Word.cc gui/MainWindow.cc build/SimpleTeacher1.0.0/ && $(COPY_FILE) --parents gui/main.ui build/SimpleTeacher1.0.0/ && (cd `dirname build/SimpleTeacher1.0.0` && $(TAR) SimpleTeacher1.0.0.tar SimpleTeacher1.0.0 && $(COMPRESS) SimpleTeacher1.0.0.tar) && $(MOVE) `dirname build/SimpleTeacher1.0.0`/SimpleTeacher1.0.0.tar.gz . && $(DEL_FILE) -r build/SimpleTeacher1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_MainWindow.cpp
build/moc_MainWindow.cpp: ui_main.h \
		Dictionary.h \
		Lexicon.h \
		Word.h \
		gui/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/MainWindow.h -o build/moc_MainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_main.h
compiler_uic_clean:
	-$(DEL_FILE) ui_main.h
ui_main.h: gui/main.ui
	/usr/bin/uic-qt4 gui/main.ui -o ui_main.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/Dictionary.o: src/Dictionary.cc src/Dictionary.h \
		src/Lexicon.h \
		src/Word.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Dictionary.o Dictionary.cc

build/Lexicon.o: src/Lexicon.cc src/Lexicon.h \
		src/Word.h \
		src/Dictionary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Lexicon.o Lexicon.cc

build/main.o: src/main.cc src/Dictionary.h \
		src/Lexicon.h \
		src/Word.h \
		gui/MainWindow.h \
		ui_main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cc

build/Word.o: src/Word.cc src/Word.h \
		src/Dictionary.h \
		src/Lexicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Word.o Word.cc

build/MainWindow.o: gui/MainWindow.cc gui/MainWindow.h \
		ui_main.h \
		Dictionary.h \
		Lexicon.h \
		Word.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindow.o gui/MainWindow.cc

build/moc_MainWindow.o: build/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindow.o build/moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

