######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 22 15:49:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . gui
INCLUDEPATH += . gui
MOC_DIR = build
RCC_DIR = build
OBJECTS_DIR = ./build


# Input
HEADERS += Dictionary.h Lexicon.h Word.h gui/MainWindow.h
FORMS += gui/main.ui
SOURCES += Dictionary.cc Lexicon.cc main.cc Word.cc gui/MainWindow.cc


